export const SWITCH_ROOM = 'SWITCH_ROOM'

export const WS_CONNECTING = 'WS_CONNECTING'
export const WS_CONNECTED = 'WS_CONNECTED'
export const WS_DISCONNECTED = 'WS_DISCONNECTED'
export const WS_MESSAGE_RECEIVED = 'WS_MESSAGE_RECEIVED'
export const WS_MESSAGE_SENT = 'WS_MESSAGE_SENT'
